Add install from web

diff --git a/buildv8 b/buildv8
--- a/buildv8
+++ b/buildv8
@@ -34,7 +34,7 @@ function print_help() {
 	echo "--configure-name=<name> Pass congiure argument to V8 build system"
 	echo "--commit=<tag-name>     Instead of compile the latest code, use the given commit"
 	echo "--install               Install the library after everthing looks good"
-	echo "--install-only          Try to install the existing build to the system"
+	echo "--install-only=[<tar>]  Try to install the existing build to the system, if a tarball is provided extract the plumber prebuilt binary from the tarball"
 	echo "--prefix=<dir>          The install prefix"
 	echo "--output=<dir>          The outout directory"
 	echo "--reconfigure           Force to re-configure the code"
@@ -47,6 +47,12 @@ function argv() {
 	else
 		realpath $(echo $1 | awk -F= '{print $2}')
 	fi
+}
+
+function extract_remote_tar() {
+	{
+		curl --silent ${1} || return 1
+	} | tar -xz || return 1
 }
 
 function parse_options() {
@@ -74,6 +80,11 @@ function parse_options() {
 				;;
 			--install-only )
 				INSTALL_ONLY="yes"
+				;;
+			--install-only=* )
+				INSTALL_ONLY="yes"
+				TAR="$(argv --string ${arg})"
+				ROOT=$(mktemp -d)
 				;;
 			--prefix=* )
 				INSTALL_PREFIX="$(argv ${arg})"
@@ -169,18 +180,6 @@ ROOT=$(pwd)
 
 parse_options $@
 
-if [ "x${INSTALL_ONLY}" = "xyes" ]
-then
-	if [ -e include ] && [ -e lib ] && [ -e data ] 
-	then
-		ACTION "Install library" install_lib
-		exit 0
-	else
-		echo "Could not find existing build of PlumberV8, you probably needs a full build"
-		exit 1
-	fi
-fi
-
 GN_DIR="${ROOT}/depot_tools"
 V8_DIR="${ROOT}/v8"
 V8_OUT="${ROOT}/v8/out.gn/${CONFNAME}"
@@ -189,6 +188,33 @@ LOG_DIR="${ROOT}/log"
 rm -rf ${LOG_DIR} 
 mkdir -p ${LOG_DIR}
 touch ${LOG_DIR}/out ${LOG_DIR}/err
+
+if [ "x${INSTALL_ONLY}" = "xyes" ]
+then
+	if [ "x${TAR}" != "x" ]
+	then
+		pushd ${ROOT}
+		if [ -z "$(echo ${TAR} | grep -E '^[a-zA-Z9-9]*://')" ]; then
+			TAR=$(realpath ${TAR})
+			ACTION "Extracting the prebuilt tarball" tar -xzf ${TAR}
+		else
+			ACTION "Extracting the prebuilt tarball from URI" extract_remote_tar ${TAR} 
+		fi
+		popd
+	fi
+	if [ -e ${ROOT}/include ] && [ -e ${ROOT}/lib ] && [ -e ${ROOT}/data ] 
+	then
+		ACTION "Install library" install_lib
+		exit 0
+	else
+		echo "Could not find existing build of PlumberV8, you probably needs a full build. Try to run:"
+		echo ""
+		echo "	./buildv8 --install-only=http://plumberserver.com/data/plumberv8-prebuild.6.3.0.x64.release.tar.gz --prefix=<install-prefix>"
+		echo ""
+		exit 1
+	fi
+fi
+
 
 pushd ${ROOT}
 #Setup GN
